# Generated by Django 2.2.10 on 2020-05-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('kcalPer100g', models.IntegerField()),
                ('proteinsPer100g', models.FloatField()),
                ('fiberPer100g', models.FloatField()),
                ('FatPer100g', models.FloatField()),
            ],
        ),
    ]
