# Generated by Django 2.2.10 on 2020-05-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlaner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='FatPer100g',
            new_name='fatPer100g',
        ),
    ]
