# Generated by Django 2.2.10 on 2020-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlaner', '0002_auto_20200509_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('typeOfMeal', models.CharField(choices=[('S', 'Sniadanie'), ('O', 'Obiad'), ('K', 'Kolacja')], max_length=2)),
                ('products', models.ManyToManyField(to='MealPlaner.Product')),
            ],
        ),
    ]
