# Generated by Django 2.2.10 on 2020-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlaner', '0003_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('products', models.ManyToManyField(blank=True, to='MealPlaner.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('products', models.ManyToManyField(blank=True, to='MealPlaner.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('products', models.ManyToManyField(blank=True, to='MealPlaner.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
