# Generated by Django 2.2.10 on 2020-05-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlaner', '0004_auto_20200512_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='MealPlaner.Product'),
        ),
    ]
