# Generated by Django 3.0.6 on 2020-05-14 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlaner', '0007_auto_20200513_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Rarely', 'Rarely'), ('Moderately', 'Moderately'), ('Often', 'Often')], max_length=10)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(50)])),
                ('target_weight', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
