# Generated by Django 3.0.6 on 2020-05-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlaner', '0008_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
